### ISSUE TITLE
step of obtaining thermocouple connected status

### ISSUE THREAD

**Issue by zhaoqiu-cn** [jordeam/max6675-esp-idf#1]
```
if (res & (1 << 14))
      ESP_LOGE(TAG, "Sensor is not connected\n");
    else {
      res >>= 3;
      printf("SPI res = %d temp=%f\n", res, res * 0.25);
    }
```

res & 0x4 is right?
`Bit  D2  is  normally  low  andgoes  high  when  the  thermocouple  input  is  open.`

**Comment by jordeam** [comment]
Yes, according to the datasheet, we need to test bit 2, I will change that. Thanks!
